# Generated by Django 4.0.4 on 2022-04-20 18:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cash_machine', '0002_receipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='title',
        ),
        migrations.AddField(
            model_name='receipt',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='receipt',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 20, 18, 58, 59, 716862, tzinfo=utc)),
        ),
    ]
